import { type AppType } from "next/app";
import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";

import { trpc } from "../utils/trpc";

import "../styles/globals.css";
import Head from "next/head";
import localFont from "@next/font/local";

/**
 * Rememeber to update the variable in tailwind.config.cjs if this gets updated
 */
const satoshiFont = localFont({
  src: "../fonts/satoshi-regular.woff2",
  variable: "--font-satoshi",
});

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <>
      <Head>
        <title>Vote Best</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SessionProvider session={session}>
        <div
          className={`flex min-h-screen w-full flex-col items-center bg-black font-sans text-white`}
        >
          <style jsx global>{`
            html {
              font-family: ${satoshiFont.style.fontFamily};
            }
          `}</style>
          <Component {...pageProps} />
        </div>
      </SessionProvider>
    </>
  );
};

export default trpc.withTRPC(MyApp);
